apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook-stg
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/morey-tech/intro-argocd-github-actions'
    path: guestbook
    targetRevision: HEAD
    helm:
      valueFiles:
        - values-stg.yaml
  destination:
    namespace: guestbook-stg
    name: dev
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
